### ISSUE TITLE
Website link is pointing to non existing bitbucket

### ISSUE THREAD

**Issue by LunicLynx** [postspectacular/toxiclibs#11]
Hello,

your website is pointing to bitbucket instead of github.

http://toxiclibs.org/downloads/

I was directed there from this example:

https://github.com/jrowberg/i2cdevlib/blob/10bcf2b49f82feec316871ac360a7e0be25b45f8/Arduino/MPU6050/examples/MPU6050_DMP6/Processing/MPUTeapot/MPUTeapot.pde#L38

Thanks for doing this

**Comment by postspectacular** [comment]
Unfortunately, the toxiclibs Wordpress installation is so ancient, that I can't seem to edit the pages anymore and I don't have the bandwidth to doctor this old site. Until recently, Bitbucket was still hosting the files (and a big notice/link to the Github mirror), but they have removed all old Mercurial repos a few months ago, causing this current trouble...

I will try to edit the links in the DB directly, but can't promise. Long term I was going to convert/backup the site as static website, since the Wordpress setup is unmaintainable.

**Comment by postspectacular** [comment]
FWIW I've just recreated a dummy repo on Bitbucket w/ a note/link to this GH repo. Hope that helps: https://bitbucket.org/postspectacular/toxiclibs/src/master/

**Comment by LunicLynx** [comment]
Good solution. 👍  Just wanted to make you aware of the situation.
