### ISSUE TITLE
Overriding Voronoi Cell site position dynamically

### ISSUE THREAD

**Issue by op-rt** [postspectacular/toxiclibs#8]
Hi,

I would like to know if it's possible to override a voronoi cell position while the sketch is iterating **without** having to clear the Voronoi() class and adding new points at every frame.

I was thinking the following  would do the trick but it didn't:

`voronoi.getSites().get(i).set(Vec2D(p.x, p.y))`

(`p` being a moving VerletParticle2D object)

For now I'm clearing/ appending points at each iteration but the frameRate drops very quickly after 100 moving particles displayed on the screen:

```
def draw():

    #Clears voronoi
    voronoi = Voronoi()
    
    for i, p in enumerate(collection):
        p.growth()
        p.display() 

        #Appending points
        voronoi.addPoint(physics.particles.get(i))
```

**Comment by postspectacular** [comment]
Unfortunately, that implementation of the algorithm does not support dynamic site updates or additions. This would require a completely different approach... In the meantime, I've since written a new version (in Typescript) which makes use of the [quad edge](http://www.cs.cmu.edu/afs/andrew/scs/cs/15-463/2001/pub/src/a2/quadedge.html) data structure. This too requires full updates, but is at least a magnitude faster compared to the toxiclibs version (e.g. 10k random sites take only ~350ms). As I already mentioned on twitter though, toxiclibs hasn't been updated really since 2011 and I'm afraid I don't have any intentions of porting or adding any new(er) features to it...

**Comment by op-rt** [comment]
Got it, thank you.
